### ISSUE TITLE
hexter_gtk segmentation error

### ISSUE THREAD

**Issue by mtarenskeen** [smbolton/hexter#10]
In Linux Fedora 30 and 31 the hexter-gui will not show up, whereas there was no such problem in Fedora 29. See: [(https://bugzilla.redhat.com/show_bug.cgi?id=1706391)](url)

running `[hexter_gtk -test]` in a terminal returns a `segmentation error` error message.

**Comment by bensmooth** [comment]
I created a pull request that fixes this: #11

**Comment by fred087** [comment]
Tried it on Archlinux and it works fine, Thx a lot

**Comment by M374LX** [comment]
Confirmed. It also segfaults for me on Void Linux.

**Comment by theabolton** [comment]
Fixed in release 1.1.1. Thanks everyone!
