### ISSUE TITLE
AM_PATH_GTK_2_0 build error on Mac OS X

### ISSUE THREAD

**Issue by jamiebullock** [smbolton/hexter#5]
Hi Sean,

I know this is only an issue with the repository version of hexter, not the release version, but still... it would be nice to be able to build out of the git repository on Mac...

So, if I run `autogen.sh`, `aclocal` complains with: 
```
configure.ac:30: warning: macro 'AM_PATH_GTK_2_0' not found in library
```

If I try the generated `configure --without-gtk2`, I get:

```
./configure: line 12219: syntax error near unexpected token `2.4.0,'
./configure: line 12219: `  AM_PATH_GTK_2_0(2.4.0, with_gtk2=yes, with_gtk2=no)'
```

It seems a shame that although it's possible to build hexter without GTK once a valid configure is generated, it's not possible to generate configure without GTK being installed!

Any ideas for a fix..?

**Comment by smbolton** [comment]
Jamie! Good to hear from you! I hope things are going well.

Ah, good old autoconf.... It expects you to at least have the macros installed for the things it is going to test for existence. I'm sure we could come up with a hack to allow building on systems without the GTK macros, but the most straightforward fix would be to just grab /usr/share/aclocal/gtk-2.0.m4 off another system and install it on your target. Is that a workable option for you?

**Comment by jamiebullock** [comment]
Thanks Sean. Yup, that works and probably better than hacking around with autoconf.

Things are good. I'll write to you in more detail soon, but Hexter will be used extensively in our Frontiers festival next week. We have updated two pieces (by Jonathan Harvey and Grisey) to use it, and the sounds are incredible: http://www.frontiersmusic.org/events/thallein-integra/
